### ISSUE TITLE
Add support for art editors for Sonic, and other maps/dplc's

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#1]
I really don't want to edit mappings manually....

**Comment by RetroKoH** [comment]
I've tested Sonic's art and mappings in Flex2, and it loads. Can you please clarify your issue? Some mapping files MIGHT have issues due to mod conditions contained within the files (I'm trying to remove this by creating alt files)

**Comment by RunninPigeon** [comment]
theres a lot of fr_ files that get erased when you use flex2 or other genesis mapping editors

**Comment by RetroKoH** [comment]
Ah. You are referring to the pointers. Ok. I will relocate those.
