### ISSUE TITLE
SRAM Support for Score, Lives, Zone, and Emeralds

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#10]
Would be very cool to have since S1 doesn't have a save option nor does it have save support, you could also add a sound when saving and have a new game and continue option on the title screen when pressing start.

**Comment by RetroKoH** [comment]
Noted. I have it running in an old 2015 build. I plan on making it optional here in the future. It'll be kept very simple but I hope it will suffice.
