### ISSUE TITLE
Speed Trails and Debug Mode causes sonic to have the sprite thats displayed in Debug Mode

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#12]
![image_2024-08-12_215643638](https://github.com/user-attachments/assets/f7d91bac-a9b1-4748-b4f2-c1fad3e92b74)

**Comment by RetroKoH** [comment]
Noted. I think I can fix this by disabling Speed Trails displaying if Debug Mode is in use. That should solve that problem.
