### ISSUE TITLE
Shield effects are semi displayed when going fast as Super Sonic

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#18]
![blastem_20240813_122934](https://github.com/user-attachments/assets/2d7026e0-7cc4-4640-990d-6c3108419383)

**Comment by RetroKoH** [comment]
Yes. If you have a shield when turning Super, the uncompressed shield art overwrites the Super Star art (which is NOT dynamically loaded in) due to them loading in the same VRAM space. Currently investigating.
