### ISSUE TITLE
Inconsistent Spacing between HUD

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#19]
![blastem_20240813_123723](https://github.com/user-attachments/assets/f9aad755-3a47-41d0-a8cb-b450a26ca44d)
Score Counter clearly looks inconsistent, there's usually a gap next to all of the HUD's

**Comment by RetroKoH** [comment]
This is actually normal if your score reaches 7 digits, across all 3 games. I am going to leave this as is.
