### ISSUE TITLE
Scrap Brain Zone Timpani Pitch Error

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#21]
It's more high pitched, rather than low pitched. It's a lot more noticeable if you have a higher quality Timpani PCM.

**Comment by RetroKoH** [comment]
Can you please test this with the MegaPCM addition build? (333519b)
I can't really tell the exact difference.

**Comment by RunninPigeon** [comment]
Yes it does, it more of a less a music file DAC error (aka sound/music/Mus06 - SBZ.asm

**Comment by RetroKoH** [comment]
That's wild, because I don't remember ever editing that file (or any of them for that matter). I wonder if something is being read incorrectly by MegaPCM2? I'll come back to this one later.

**Comment by RetroKoH** [comment]
I am listening to this between Fixed and stock S1, along with ReadySonic, and a clean S1 with MegaPCM2 and they sound identical. I even had a few other modders give it a look/listen and they are reporting there is no issue. I will close this for now and chock it up to an anomaly, or possible emulation issue.

**Comment by RunninPigeon** [comment]
According to Mastered Realm in a [YouTube comment](https://www.youtube.com/watch?v=66JXk4666GY): 

> There are two timpanis (special kind of drum) in different in the percussion, and when compared to Masa's demo, the pitches
> are all inverted! For example, when the timpanis are Hi, Hi, Lo, Hi, they are 'Lo, Lo, Hi, Lo' in Sonic 1. So probably the Sonic 1
> driver changed after this song was added, as all other songs with timpanis match the demo!

this could be solved by inverting the timpani pitches, simple as that! :)

**Comment by RetroKoH** [comment]
Ah... so you're saying there is an alternate version (based on the demo) that has inverted timpani pitches?

Perhaps this can be a minor elective mod.

**Comment by RunninPigeon** [comment]
Yeah, but that was the original version before it was transferred onto the Genesis/Mega Drive
