### ISSUE TITLE
Selecting Continue from Title Screen without any saves crashes the game

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#29]

**Comment by RetroKoH** [comment]
That's weird. I thought I tested that. It was supposed to start you off in a new game. Which emulator did you test with?

**Comment by RunninPigeon** [comment]
BlastEm

**Comment by RunninPigeon** [comment]
I also decided to launch up in ClownMDEmu and heres what i got, i can't even pause
![SONIC THE HEDGEHOG 8_14_2024 5_02_48 PM](https://github.com/user-attachments/assets/275a39bd-4be6-4733-9f1e-dccaf284e474)

**Comment by RetroKoH** [comment]
Ok that is REALLY bizarre. I'll look into both. I don't see how the latter is connected to the Saving mod tho, and if it isnt I need to see why that happens.
