### ISSUE TITLE
256x256 Chunk with Extended Rom Chunks to $FF Branch

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#3]
Would be useful for level making.

**Comment by RetroKoH** [comment]
Closing this. It is under consideration, but early looks suggest that this will NOT be possible unless 16x16 blocks are ALWAYS uncompressed in ROM when 256x256 mode is active. Branch opened, but I am shelving this for now.

**Comment by RunninPigeon** [comment]
Needs to be opened up again, SonLVL Break when using S1/ 256x256 chunks

**Comment by RunninPigeon** [comment]
changing the chunkfmt from S2 to S1, it causes weird glitchy tiles

**Comment by RetroKoH** [comment]
> changing the chunkfmt from S2 to S1, it causes weird glitchy tiles

This is because the format of the chunk files in S1Fixed cannot be read like S1 chunks. They were converted to S2 format in the base conversion to One: Two-Eight. Until it's possible to toggle chunk sizes, this setting must be left at S2.
