### ISSUE TITLE
Weird top screen black line

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#33]
This happens when you have too many monitors, no idea why this happens
![image_2024-08-21_131333722](https://github.com/user-attachments/assets/a46e1226-c9e3-4ef0-be46-61563ce0f6f2)

**Comment by RetroKoH** [comment]
Is this purely in Debug Mode? Or have you also observed this in regular gameplay too?

**Comment by RunninPigeon** [comment]
I probably think this has something to do with the actual monitor icon and it somehow teleporting to the top of the screen, not noticed it in regular gameplay though, haven't done that yet

**Comment by RetroKoH** [comment]
If you can replicate it, please share a full screenshot along with what exactly happened. If it can potentially happen in non-debug gameplay, I wanna fix it.

**Comment by RunninPigeon** [comment]
![blastem_20240821_225447](https://github.com/user-attachments/assets/47fc04c0-fa01-4f9d-b9e0-4eca7210ea9c)
okay then

**Comment by RetroKoH** [comment]
I didn't see it trigger on mine. For now, I'm going to chock it up to too many sprites on screen as a result of Debug Mode.
