### ISSUE TITLE
Disable all abilities when using debug mode

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#39]

**Comment by RetroKoH** [comment]
As in don't allow Sonic to do these? Or is there a bug if entering Debug mode while using them? Please provide more details.

**Comment by RunninPigeon** [comment]
![blastem_20240912_211356](https://github.com/user-attachments/assets/07c99049-9e0e-4f6b-a0a5-8da28148f71e)
you can see the spin dash dust

**Comment by DeltaWooloo** [comment]
Fixed the issue - spindash flag doesn't get cleared when you enter debug mode
