### ISSUE TITLE
Quickly using the fire shield causes the fire dash to persist.

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#4]
![image_2024-08-09_125940081](https://github.com/user-attachments/assets/da4dad0a-b999-412b-ae6d-cdefcc4ece62)
(im not moving at all)

**Comment by RetroKoH** [comment]
When you say this persists, do you simply mean that the animation doesn't end upon landing? Or that the animation doesn't stop?

**Comment by RunninPigeon** [comment]
animation doesn't end upon landing and the animation doesn't stop

**Comment by RetroKoH** [comment]
> animation doesn't end upon landing
This one, I can confirm happens in the original S3K. I can fix it.
> and the animation doesn't stop
I haven't been able to replicate this, but I have a feeling that if I fix the first issue, it should fix this also. I'll update later today.
