### ISSUE TITLE
Per Act Music Option

### ISSUE THREAD

**Issue by AnxiousRexy** [RetroKoH/S1Fixed#44]
The title says it all. This could be good for people that know how to port music like myself that want to see their ports in their hack. Also I am new to github so I don't know how to label this as a request right this moment.

**Comment by DeltaWooloo** [comment]
Could be a useful option. I'll mark it as a feature and see what KoH has to say about this.

**Comment by AnxiousRexy** [comment]
> Could be a useful option. I'll mark it as a feature and see what KoH has to say about this.

Cool thanks. My goal is to convert my old hack into this disasm and that music bit was part of it. Sadly idk if I can convert my old layouts with the one two eight format, so might have to make new levels if thats the case.

**Comment by RetroKoH** [comment]
I already have a system planned (not coded yet). Delta, if you already have it in the works, please feel free to implement if/when you feel it's ready. Only thing I ask is that by default, we leave track options to default (much like how I did the per act palette option).
