### ISSUE TITLE
Goggles Overlay on Sonic doesn't display the correct corresponding animations

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#52]
![image_2024-12-13_000722366](https://github.com/user-attachments/assets/aea92c7a-5d13-42ff-b97c-3fbf8ee0727c)

**Comment by RetroKoH** [comment]
Intentional. It's incomplete atm on account of my being busy with other features and optimizations atm. I will tackle this and Super Sprites in a future update.
