### ISSUE TITLE
Drop dash can't be used when having Invincibility or the Blue shield

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#7]
Weird how it treats the shields as unusable shields...

**Comment by RetroKoH** [comment]
An oversight on my part. To that end, if I have an elemental shield and then get invincibility afterward, should I still be able to drop dash?

**Comment by RunninPigeon** [comment]
You should still be able to drop-dash until the invincibility wears out.

**Comment by RunninPigeon** [comment]
still can't use dropdash when having elemental shields and invincibility

**Comment by RetroKoH** [comment]
That's because I haven't gotten to that yet. It will require another refactoring of Sonic_JumpHeight.

**Comment by RunninPigeon** [comment]
ok then closing some now

**Comment by RetroKoH** [comment]
In the future pls don't close until I commit fixes. It will make it a little easier to keep track of what needs done.

**Comment by RunninPigeon** [comment]
sorry

**Comment by RetroKoH** [comment]
> Author

No need. I really appreciate the reports and suggestions

**Comment by RetroKoH** [comment]
Fixed. There is a minor bug that makes for a nice gameplay feature I'm going to keep. If you bubble bounce into an Invinc or S monitor, and keep the button held down, you can transition right into the Drop Dash.
