### ISSUE TITLE
Outdated Flex2 Project File

### ISSUE THREAD

**Issue by RunninPigeon** [RetroKoH/S1Fixed#9]
![image_2024-08-12_105626754](https://github.com/user-attachments/assets/5e52e454-9a02-4c29-a733-864fa31024a4)

**Comment by RunninPigeon** [comment]
As well as the ASM Labels too

**Comment by RetroKoH** [comment]
All currently listed objects should now work. If any don't, please reopen this issue. I also added the Shields. Might split Blue Shield and Inv Stars mappings later.
